version: '3'

services:
  annotate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: annotate
    hostname: annotate
    volumes:
      - ./local.properties:/root/LEOS/modules/annotate/config/src/main/filters/local.properties
    ports:
      - "9099:9099"
    command: ./run-annotate.sh
    restart: always
  user-repository:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: user-repository
    hostname: user-repository
    ports:
      - "9095:9095"
    command: ./run-user-repository.sh
    restart: always
  repository:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repository
    hostname: repository
    ports:
      - "9090:9090"
    command: ./run-repository.sh
    restart: always
  leos:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: leos
    hostname: leos
    ports:
      - "8080:8080"
    volumes:
      - ./leos.properties:/root/LEOS/modules/config/src/main/filters/leos.properties
      - ./run-leos.sh:/root/LEOS/run-leso.sh
    command: ./run-leos.sh
    restart: always
    depends_on:
      - annotate
      - user-repository
      - akn4euutil
      - repository
  akn4euutil:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: akn4euutil
    hostname: akn4euutil
    restart: always
    ports:
      - "9096:9096"
    command: ./run-akn4euutil.sh
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - leos
